name = "nftdrop"
type = "javascript"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-20"

[durable_objects]
bindings = [
  { name = "DISCORD", class_name = "Discord" },
  { name = "TWITTER", class_name = "Twitter" },
  { name = "NFTDROP", class_name = "Nftdrop" },
  { name = "NEAR", class_name = "Near" }
]

[[migrations]]
tag = "v1"
new_classes = ["Discord", "Nftdrop", "Twitter"]

[[migrations]]
tag = "v2"
new_classes = ["Near"]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"
