name = "nftdrop"
type = "javascript"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-20"

kv_namespaces = [
  { binding = "DISCORD_SESSIONS", id = "70735ef939e24dc49a85172cf7f934f8" },
  { binding = "TWITTER_SESSIONS", id = "d761e56521fe49589b772a6a43024a31" }
]

[vars]
DATE_THRESHOLD = "2022-02-15"
RETWEET_ID = "1468678836632133638"

[durable_objects]
bindings = [
  { name = "DISCORD", class_name = "Discord" },
  { name = "TWITTER", class_name = "Twitter" },
  { name = "NFTDROP", class_name = "Nftdrop" },
  { name = "NEAR", class_name = "Near" }
]

[[migrations]]
tag = "v1"
new_classes = ["Discord", "Nftdrop", "Twitter"]

[[migrations]]
tag = "v2"
new_classes = ["Near"]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"

[env.production]
workers_dev = false
zone_id = "f0cc6af324b9ef33f40a1ef5edf5b1fd"
routes = [
  "nftdrop-api.shroomkingdom.net/*"
]
kv_namespaces = [
  { binding = "DISCORD_SESSIONS", id = "7b74b5b2dd24497298b03e84814febda" },
  { binding = "TWITTER_SESSIONS", id = "b325cecbbbe54a51908fa809d81db9d8" }
]

[env.production.vars]
DATE_THRESHOLD = "2022-02-15"
RETWEET_ID = "1468678836632133638"

[env.production.durable_objects]
bindings = [
  { name = "DISCORD", class_name = "Discord" },
  { name = "TWITTER", class_name = "Twitter" },
  { name = "NFTDROP", class_name = "Nftdrop" },
  { name = "NEAR", class_name = "Near" }
]

[[env.production.migrations]]
tag = "v1"
new_classes = ["Discord", "Nftdrop", "Twitter", "Near"]
